### ISSUE TITLE
Неработещ линк за SDL2 Visual Studio setup

### ISSUE THREAD

**Issue by googleson78** [stranxter/lecture-notes#6]
В Makefile-а https://github.com/stranxter/lecture-notes/blob/master/samples/01_programming%20101/2016/01_plotting%20pixels/Makefile
link-а за setup на SDL2 на Visual Studio не е работещ линк, последната / води в несъществуваща директория, линкът трябва да е
http://www.willusher.io/sdl2%20tutorials/2013/08/15/lesson-0-visual-studio
Може би ще е по-удобно ако има link направо към по-общото 
http://www.willusher.io/sdl2%20tutorials/2013/08/15/lesson-0-setting-up-sdl

**Comment by stranxter** [comment]
Искаш ли да дадеш pull request :)
